### ISSUE TITLE
Problem running npm run devserver

### ISSUE THREAD

**Issue by PierreBresson** [shprink/wordpress-hybrid-client#104]
Hi,

When I do npm run deserver, I have the following errors : 

<img width="736" alt="screen shot 2015-11-03 at 16 19 48" src="https://cloud.githubusercontent.com/assets/8709134/10913708/1ceca5c8-8247-11e5-9f24-2ea83cc060f0.png">

Any idea how to this that ?

Cheers :)

**Comment by shprink** [comment]
yeah, that is fixed in develop. What version are you using?

**Comment by shprink** [comment]
add this line to webpack.config.js https://github.com/shprink/wordpress-hybrid-client/blob/develop/webpack.config.js#L22

**Comment by PierreBresson** [comment]
I checkout the latest version available as requested in the installation.md so I'm using v2.0.0-alpha1.
Ok I ll add the line and see if it is working.
Thanks for your quick answer and congratulation for this app which seems very promising ;)

**Comment by PierreBresson** [comment]
Yep, it's working, thanks :)

**Comment by shprink** [comment]
hehe but be careful v2.0.0-alpha1 is an alpha version, we are still testing it. v1.7.1 is the latest stable version

**Comment by PierreBresson** [comment]
Hum "npm run devserver" is working very well but npm run runAndroid is not launching the app on my android phone (and don't give any me any error) and when my phone is not plugged it doesn't launch the emulator. 

<img width="662" alt="screen shot 2015-11-03 at 18 48 26" src="https://cloud.githubusercontent.com/assets/8709134/10918040/8e31aa08-825b-11e5-9259-3bbc50c15d95.png">

Yep I tried to install v1.7.1 (and also v1.7.0) but after "npm run installWPHC" there is no config folder. Here is exactly what I did : 
git clone https://github.com/shprink/wordpress-hybrid-client.git
cd wordpress-hybrid-client
git checkout v1.7.1
npm install
npm run installWPHC

Did I write something wrong ?

**Comment by shprink** [comment]
v1.x does not have a config folder. https://github.com/shprink/wordpress-hybrid-client/blob/v1.7.1/INSTALLATION.md#config-files

**Comment by PierreBresson** [comment]
Oh I see, sorry.
Same thing as the v2 alpha, v1.7.1 is running well on my computer but "npm run runAndroid" is not launching the app on my android phone.

**Comment by shprink** [comment]
try `adb devices` to see if your device is register

**Comment by PierreBresson** [comment]
Yes I can see my devices when I do adb devices.

I also build a small app android app today using Ionic 2 so android sdk should be well installed (but I'm not sure 100%, I'm new to ionic).

**Comment by shprink** [comment]
if you have cordova globally installed try using directly cordova or ionic commands. `cordova run android`

**Comment by PierreBresson** [comment]
I tried both and nothing (and also npm rebuild node-sass as said in the error message).

<img width="584" alt="screen shot 2015-11-03 at 22 23 11" src="https://cloud.githubusercontent.com/assets/8709134/10923536/82e60086-8279-11e5-87b0-3aeb77da21d7.png">

**Comment by shprink** [comment]
what's your npm version? it needs to be > 3.x

**Comment by shprink** [comment]
I had this problems several times and running `npm rebuild node-sass` generally fix it

**Comment by PierreBresson** [comment]
it's 3.3.6

**Comment by shprink** [comment]
Chat is better to debug together => https://gitter.im/shprink/wordpress-hybrid-client

**Comment by shprink** [comment]
Never tried node 5.x it evolves so quickly...

**Comment by shprink** [comment]
if someone is browsing this ticket, running node 4.x (as stated in the documentation) will solve the problem.

**Comment by Prabhat36** [comment]
error when i run this command please help:  npm run runAndroid





npm ERR! wordpress-hybrid-client@2.0.0-alpha2 runAndroid: `npm run dumpdev && cordova run android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wordpress-hybrid-client@2.0.0-alpha2 runAndroid script.
npm ERR! This is most likely a problem with the wordpress-hybrid-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dumpdev && cordova run android
npm ERR! You can get their info via:
npm ERR!     npm owner ls wordpress-hybrid-client
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-16-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "runAndroid"
npm ERR! cwd /home/prabhat/wordpress-hybrid-client
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/prabhat/wordpress-hybrid-client/npm-debug.log
npm ERR! not ok code 0
