### ISSUE TITLE
Push notif does not open post when app not opened

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#208]
if app current app or in background it is fine
if not opened then home page

**Comment by Prabhat36** [comment]
PUSH NOTIFICATION NOT WORKING @shprink 
installed app on device ,  i did everything correctly.
but not working the debug error is attached,,
![apikey](https://cloud.githubusercontent.com/assets/14105960/14600968/00e7ae0e-057d-11e6-9dcd-5ed1267fc0b5.png)

**Comment by shprink** [comment]
@Prabhat36 your error is in the docs https://github.com/shprink/wordpress-hybrid-client/blob/develop/PUSHNOTIFICATIONS.md#known-issues

**Comment by AsadAlihp** [comment]
hey guys. I was having the problem with push notifications. but worked fine for me after removing space.
> original `"enabled": true` to `"enabled":true`

**Comment by Prabhat36** [comment]
thanks a lot @shprink  @AsadAlihp

**Comment by barbax** [comment]
Hey guys.. it's not clear to me the normal behaviour the app should have on push notification and i can fix this if there are problems since i'm fixing this on my fork of the app.

If the app is close or in background, what is expected to do? The notification are working fine, but if the app it's close the notification just open the app to the default page. Is that what is expected to be or i just broke something?

B/R

**Comment by shprink** [comment]
The expected behavior is to open the post exactly the same as with v1. It
is broken, should be an easy fix, PR very welcomed :)

**Comment by barbax** [comment]
ahhn.. ok. I've had this issue in an other cordova app.. hope to fix this and to share the solution soon. btw..thanx for the great job you have done!
