### ISSUE TITLE
Problem making customs templates

### ISSUE THREAD

**Issue by ryan-0** [shprink/wordpress-hybrid-client#273]
Hi, 
I'm trying to use the client for the following website: http://tuftsdaily.com/   
where each menu item is a navigation item on the website (News, Features, Arts, etc.)
However, I'm having trouble linking http://tuftsdaily.com/wp-json to the menu items. 
I understand I'm supposed to add my Custom Posts in the templates/customPosts folder and then register them in the templates/index.js file but I can't get it to work. Any help would be appreciated. 
Thanks!

**Comment by shprink** [comment]
Does it work with my own web service? If you follow the quick start steps you will have custom posts working (movies & actor)

**Comment by ryan-0** [comment]
yes it works with your web service with no problem.

**Comment by shprink** [comment]
Then you have a working example. Just create new menu item that point to your custom posts types and register new templates for it.
Make sure when you open you custom posts page that the http request is correct (use chrome dev tools tab: Network)
Closing because that's not an issue. If you need any help join the chat https://gitter.im/shprink/wordpress-hybrid-client
