### ISSUE TITLE
Push notification by delitestudio full integration

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#83]
Documentation: http://www.delitestudio.com/wordpress/push-notifications-for-wordpress/documentation/

Missing:

- Unregister globally
- Register/Unregister to a specific category 
- Notify the plugin when a PN is read (see Posts API (details))

Related to #69

**Comment by delitestudio** [comment]
We have implemented a new official API you can use to set a post as viewed.
We have released it in https://wordpress.org/plugins/push-notifications-for-wp/developers/ under Development Version

URL structure:
* http://yoursite/pnfw/posts/

Method:
* POST

Parameters:
* token (string): token given by APNs, GCM, or ADM identifying the device, often called device ID (read here for devices without token, e.g. iOS simulator).
* os (string): operating system. It must be iOS, Android, or Fire OS (case sensitive).
* id (integer): the ID of the post.
* viewed (boolean): whether or not the post has to be set as viewed.

Sample request:
```
POST /pnfw/posts/ HTTP/1.1
Host: yoursite
Content-Length: 40
Content-Type: application/x-www-form-urlencoded

token=device_id&os=iOS&id=3&viewed=true
```

**Comment by shprink** [comment]
Awesome thanks @delitestudio :)

**Comment by delitestudio** [comment]
We have just released the 1.4 version of Push Notifications for Wordpress (Lite) with the new API.

**Comment by shprink** [comment]
Awesome,

I will check this out pretty soon :)

**Comment by delitestudio** [comment]
We have officially suggested WordPress Hybrid Client:
> Works with native apps, Cordova, Ionic, PhoneGap, and more frameworks. Build beautiful and interactive mobile apps using your preferred technology. We suggest WordPress Hybrid Client to build amazing applications effortless.

on https://it.wordpress.org/plugins/push-notifications-for-wp/

**Comment by shprink** [comment]
thanks @delitestudio :)

**Comment by delitestudio** [comment]
We have implemented a filter that allow us to intercept parameters (os and token) and identify which user is retrieving the list of posts or a specific post (we have released it in https://wordpress.org/plugins/push-notifications-for-wp/developers/ under Development Version).

The only thing you have to do on your side is to call the posts WP REST API endpoint with os and token parameters as in this example:
* http://server/wp-json/wp/v2/posts?os=iOS&token=device_id
* http://server/wp-json/wp/v2/posts/200?os=iOS&token= device_id

When we discover a specific post has been retrieved with WP REST API we set it as viewed.

When we discover a list of posts has been retrieved we set a boolean flag “read” on each post so you can use this information to display them as “read/unread” (like for example a Mail client).

At the moment we cannot support custom post types but we will support them in future releases.

**Comment by shprink** [comment]
great stuff!

**Comment by shprink** [comment]
@delitestudio Android is now OK:

![image](https://cloud.githubusercontent.com/assets/1388706/11857301/8be5ff50-a41c-11e5-91be-9daa50b2d817.png)

The new code lives here: https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/cordova/cordova.pushNotifications.js#L56-L68

I still need to test on iOS but so far even with valid .pem I have the following error message:

Unable to connect to 'tls://gateway.sandbox.push.apple.com:2195': (0)

Any idea?

**Comment by delitestudio** [comment]
Good work @shprink! [Here](http://www.delitestudio.com/wordpress/push-notifications-for-wordpress/faqs/) you can find the official FAQ:

Why am I getting the error Unable to connect to tsl://gateway.push.apple.com:2195?
Your server is unable to connect to the push service.

This can be caused by:
* The SSL certificate you are using, which is invalid or it has expired (remember that a certificate is valid for 1 year).
* The certificate password you specified, which is not correct.
* The fact that you are using a production certificate instead of a development one.
* The fact that Push Notifications for WordPress can't receive inbound and outbound TCP packets over ports 2195 and 2196.

**Comment by delitestudio** [comment]
You can now add the parameters to this call when retrieving posts:

* http://server/wp-json/wp/v2/posts?os=iOS&token=device_id

We set a boolean flag “read” on each post so you can use this information to display them as “read/unread” (like for example a Mail client).

It's useful to discover unread posts when users accidentally close notifications.

**Comment by maxlinux2000** [comment]
@delitestudio

Hi, sorry for the OT,

but I'm searching a way to implement the push plugin for cordova in order to connect to your plugin in wordpress.

my app is in cordova (phonegap) and the plugin that I want to use is the same of these (very great) app for ionic.

I tried to use the example in the https://github.com/phonegap/phonegap-plugin-push
but the token can't arrive to wordpress.
...and this ionic app is very "uglify" ;-) and I can't understand how is working.

Can you help me?

**Comment by shprink** [comment]
what do you mean by "uglify" ?

The code is here: https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/cordova/cordova.pushNotifications.js

**Comment by maxlinux2000** [comment]
Sorry if I said wrong. I mean that using the webpack and uglify modules, it is difficult for me  follow your code works, which by the way is very very good.

**Comment by shprink** [comment]
I think we have all the features we wanted.
